services:
  postgres-db:
    image: postgres:16.3
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  my-go-server:
    image: my-go-server
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  postgres-data:
